services:
  frontend:
    image: ellarbee/group-ironmen-tracker-frontend
    build:
      context: ./site
      dockerfile: Dockerfile
    container_name: gimp-frontend
    restart: always
    environment:
      - HOST_PROTOCOL=${HOST_PROTOCOL}
      - HOST_URL=${HOST_URL}
    ports:
      - 4000:4000 # Needs to be changed if using a reverse proxy, nonstandard ports for frontend/backend, or forwarding a different port on the host.
  backend:
    image: ellarbee/group-ironmen-tracker-backend
    build:
      context: ./server
      dockerfile: Dockerfile
    depends_on:
      - "postgres"
    container_name: gimp-backend
    restart: always
    environment:
      - PG_USER=${PG_USER}
      - PG_PASSWORD=${PG_PASSWORD}
      - PG_HOST=${PG_HOST}
      - PG_PORT=${PG_PORT}
      - PG_DB=${PG_DB}
      - BACKEND_SECRET=${BACKEND_SECRET}
    # Uncomment this if you don't want/need to use a reverse-proxy, and need docker to map the ports.
    # ports:
    #   - 5000:8080 # Needs to be changed if using a reverse proxy, nonstandard ports for frontend/backend, or forwarding a different port on the host.
  postgres:
    image: postgres
    container_name: gimp-postgres
    restart: always
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
    volumes:
      # Maps the container's postgres data folder to a host-side folder. Change the left hand side to where you prefer postgres to save data to.
      - ./pg-data:/var/lib/postgresql/data
      - ./server/src/sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
  nginx:
    image: nginx:1.27
    container_name: gimp-nginx
    restart: always
    environment:
      - FRONTEND_HOST=${FRONTEND_HOST}
    ports:
      - 5000:3333
    volumes:
      - ./templates:/etc/nginx/templates
