services:
  group-ironmen-tracker-frontend:
    build:
      context: ./site
      dockerfile: Dockerfile
    image: ellarbee/group-ironmen-tracker-frontend
    environment:
      - HOST_PROTOCOL=${HOST_PROTOCOL}
      - HOST_URL=${HOST_URL}
    restart: always
    container_name: group-ironmen-tracker-frontend
    ports:
      - 4000:4000 # replace this if using a docker-compatible reverse proxy like traefik
  group-ironmen-tracker-backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: ellarbee/group-ironmen-tracker-backend
    environment:
      - PG_USER=${PG_USER}
      - PG_PASSWORD=${PG_PASSWORD}
      - PG_HOST=${PG_HOST}
      - PG_PORT=${PG_PORT}
      - PG_DB=${PG_DB}
      - BACKEND_SECRET=${BACKEND_SECRET}
    restart: always
    depends_on:
      - "postgres"
    container_name: group-ironmen-tracker-backend
  # Uncomment this if you don't want/need to use a reverse-proxy, and need docker to map the ports.
  # ports:
  #   - 5000:8080 # Needs to be changed if using a reverse proxy, nonstandard ports for frontend/backend, or forwarding a different port on the host.
  postgres:
    image: postgres
    restart: always
    container_name: group-ironmen-tracker-postgres
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
    volumes:
      - ./pg-data:/var/lib/postgresql/data # change the left-hand side of : to the path you prefer the DB to store the data in
      - ./server/src/sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql # change the left-hand side of the : to the path that contains the schema.sql
  nginx:
    image: nginx:1.27
    container_name: group-ironmen-tracker-nginx
    restart: always
    environment:
      - FRONTEND_HOST=${FRONTEND_HOST}
    ports:
      - 5000:3333
    volumes:
      - ./templates:/etc/nginx/templates
